import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(packageRoot, "../..");

const copies = [
  ["crates/texform-wasm/pkg/texform_wasm.js", "wasm/nodejs/texform_wasm.cjs"],
  ["crates/texform-wasm/pkg/texform_wasm_bg.wasm", "wasm/nodejs/texform_wasm_bg.wasm"],
  ["crates/texform-wasm/pkg/texform_wasm.d.ts", "wasm/nodejs/texform_wasm.d.ts"],
  ["crates/texform-wasm/pkg/texform_wasm_bg.wasm.d.ts", "wasm/nodejs/texform_wasm_bg.wasm.d.ts"],
  ["crates/texform-wasm/pkg-web/texform_wasm.js", "wasm/web/texform_wasm.js"],
  ["crates/texform-wasm/pkg-web/texform_wasm_bg.wasm", "wasm/web/texform_wasm_bg.wasm"],
  ["crates/texform-wasm/pkg-web/texform_wasm.d.ts", "wasm/web/texform_wasm.d.ts"],
  ["crates/texform-wasm/pkg-web/texform_wasm_bg.wasm.d.ts", "wasm/web/texform_wasm_bg.wasm.d.ts"],
];

await rm(resolve(packageRoot, "wasm"), { recursive: true, force: true });

for (const [from, to] of copies) {
  const source = resolve(repoRoot, from);
  const target = resolve(packageRoot, to);
  await mkdir(dirname(target), { recursive: true });
  await copyFile(source, target);
}

// Generate the CommonJS entry from the shared ESM bindings so the two cannot drift.
const shared = await readFile(resolve(packageRoot, "shared/create-bindings.js"), "utf8");
const body = shared.replace(/^export function createBindings/m, "function createBindings");
if (body === shared) throw new Error("shared/create-bindings.js must export createBindings");
await writeFile(
  resolve(packageRoot, "node/index.cjs"),
  `// Generated by scripts/sync-wasm.mjs from shared/create-bindings.js.
const wasm = require("../wasm/nodejs/texform_wasm.cjs");
${body}
module.exports = createBindings({
  ...wasm,
  validateArgspec: wasm.validate_argspec,
});
`,
);
