//! Build script that auto-discovers rule `.rs` files in `src/transform/rules/`
//! and generates a `rules_registry.rs` module that re-exports them all.
//!
//! Convention: every file under `src/transform/rules/` (except `mod.rs`) must
//! declare exactly one `pub static UPPER_SNAKE: SomeRuleType` whose name is the
//! UPPER_SNAKE_CASE form of the file stem. The generated registry `include!`s
//! the module declarations with absolute `#[path]` attributes (so they resolve
//! correctly from `OUT_DIR`) and aggregates every rule constant into `ALL_RULES`.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{collections::BTreeMap, env, fs};

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct RuleEntry {
    relative_path: PathBuf,
    module_name: String,
    constant_name: String,
}

fn encode_module_name(relative_path: &Path) -> String {
    let mut module_name = String::from("rule");

    for component in relative_path.with_extension("").iter() {
        let component = component.to_str().unwrap();
        write!(module_name, "_{}_", component.len()).unwrap();
        for byte in component.bytes() {
            match byte {
                b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'_' => {
                    module_name.push(byte as char);
                }
                _ => {
                    write!(module_name, "_x{byte:02x}").unwrap();
                }
            }
        }
    }

    module_name
}

fn collect_rule_entries(base_dir: &Path, dir: &Path, entries: &mut Vec<RuleEntry>) {
    let mut children: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", dir.display()))
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .collect();
    children.sort();

    for path in children {
        if path.is_dir() {
            collect_rule_entries(base_dir, &path, entries);
            continue;
        }

        let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if file_name == "mod.rs" || path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
            continue;
        }

        let relative_path = path.strip_prefix(base_dir).unwrap().to_path_buf();
        let stem = path.file_stem().and_then(|stem| stem.to_str()).unwrap();
        let module_name = encode_module_name(&relative_path);

        entries.push(RuleEntry {
            relative_path,
            module_name,
            constant_name: stem.to_uppercase(),
        });
    }
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let rules_dir = Path::new(&manifest_dir).join("src/transform/rules");
    let out_dir = env::var("OUT_DIR").unwrap();

    // Re-run if any file in the rules directory changes.
    println!("cargo:rerun-if-changed={}", rules_dir.display());

    let mut entries = Vec::new();
    collect_rule_entries(&rules_dir, &rules_dir, &mut entries);

    let mut seen_module_names = BTreeMap::new();
    for entry in &entries {
        if let Some(existing_path) =
            seen_module_names.insert(&entry.module_name, &entry.relative_path)
        {
            panic!(
                "duplicate generated module name '{}' for '{}' and '{}'",
                entry.module_name,
                existing_path.display(),
                entry.relative_path.display()
            );
        }
    }

    // Sort by relative path for deterministic output.
    entries.sort();

    let mut code = String::new();

    writeln!(
        code,
        "// Auto-generated by build.rs — do not edit.\n\
         //\n\
         // Builtin transform rule registry. Every `.rs` file under\n\
         // `src/transform/rules/` (except `mod.rs`) is automatically\n\
         // registered here.\n"
    )
    .unwrap();

    writeln!(code, "use crate::transform::rule::TransformRule;\n").unwrap();

    // Emit `#[path = "..."] pub mod <name>;` for each rule file.
    // The absolute path ensures `include!` from OUT_DIR can find the source.
    for entry in &entries {
        let abs_path = rules_dir.join(&entry.relative_path);
        writeln!(
            code,
            "#[path = \"{}\"]",
            abs_path.display().to_string().replace('\\', "/")
        )
        .unwrap();
        writeln!(code, "pub mod {};", entry.module_name).unwrap();
    }

    // Build the ALL_RULES slice, referencing each rule's UPPER_SNAKE constant.
    writeln!(code).unwrap();
    writeln!(
        code,
        "pub(crate) static ALL_RULES: &[&dyn TransformRule] = &["
    )
    .unwrap();
    for entry in &entries {
        writeln!(code, "    &{}::{},", entry.module_name, entry.constant_name).unwrap();
    }
    writeln!(code, "];").unwrap();

    let out_path = Path::new(&out_dir).join("rules_registry.rs");
    fs::write(&out_path, code).expect("failed to write rules_registry.rs");
}

#[cfg(test)]
mod tests {
    use super::encode_module_name;
    use std::path::Path;

    #[test]
    fn module_name_encoding_keeps_nested_paths_distinct() {
        assert_ne!(
            encode_module_name(Path::new("a/b_c.rs")),
            encode_module_name(Path::new("a_b/c.rs"))
        );
    }

    #[test]
    fn module_name_encoding_stays_within_rust_identifier_charset() {
        let name = encode_module_name(Path::new("physics/trace-alias/trace_to_tr.rs"));
        assert!(name.starts_with("rule_"));
        assert!(
            name.chars()
                .all(|ch| ch.is_ascii_alphanumeric() || ch == '_')
        );
    }
}
