//! Build script that auto-discovers rule `.rs` files in `src/transform/rules/`
//! and generates a `rules_registry.rs` module that re-exports them all.
//!
//! Convention: every file in `src/transform/rules/` (except `mod.rs`) must
//! declare exactly one `pub static UPPER_SNAKE: SomeRuleType` whose name is the
//! UPPER_SNAKE_CASE form of the file stem. The generated registry `include!`s
//! the module declarations with absolute `#[path]` attributes (so they resolve
//! correctly from `OUT_DIR`) and aggregates every rule constant into `ALL_RULES`.

use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let rules_dir = Path::new(&manifest_dir).join("src/transform/rules");
    let out_dir = env::var("OUT_DIR").unwrap();

    // Re-run if any file in the rules directory changes.
    println!("cargo:rerun-if-changed={}", rules_dir.display());

    let mut entries: Vec<String> = fs::read_dir(&rules_dir)
        .expect("failed to read src/transform/rules/")
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let name = entry.file_name().into_string().ok()?;
            if name == "mod.rs" || !name.ends_with(".rs") {
                return None;
            }
            Some(name.trim_end_matches(".rs").to_owned())
        })
        .collect();

    // Sort for deterministic output.
    entries.sort();

    let mut code = String::new();

    writeln!(
        code,
        "// Auto-generated by build.rs — do not edit.\n\
         //\n\
         // Builtin transform rule registry. Every `.rs` file in\n\
         // `src/transform/rules/` (except `mod.rs`) is automatically\n\
         // registered here.\n"
    )
    .unwrap();

    writeln!(code, "use crate::transform::rule::TransformRule;\n").unwrap();

    // Emit `#[path = "..."] pub mod <name>;` for each rule file.
    // The absolute path ensures `include!` from OUT_DIR can find the source.
    for name in &entries {
        let abs_path = rules_dir.join(format!("{name}.rs"));
        writeln!(
            code,
            "#[path = \"{}\"]",
            abs_path.display().to_string().replace('\\', "/")
        )
        .unwrap();
        writeln!(code, "pub mod {name};").unwrap();
    }

    // Build the ALL_RULES slice, referencing each rule's UPPER_SNAKE constant.
    writeln!(code).unwrap();
    writeln!(
        code,
        "pub(crate) static ALL_RULES: &[&dyn TransformRule] = &["
    )
    .unwrap();
    for name in &entries {
        let constant = name.to_uppercase();
        writeln!(code, "    &{name}::{constant},").unwrap();
    }
    writeln!(code, "];").unwrap();

    let out_path = Path::new(&out_dir).join("rules_registry.rs");
    fs::write(&out_path, code).expect("failed to write rules_registry.rs");
}
